{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "mysql-operator.fullname" . }}
  labels:
    app: {{ template "mysql-operator.name" . }}
    chart: {{ template "mysql-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ["mysql.presslabs.org"]
    resources: ["mysqlclusters", "mysqlbackups"]
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - endpoints
      - configmaps
      - secrets
      - events
      - services
      - pods
      - jobs
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
  {{- if .Values.installCRDs }}
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    # deletion of a crd is not allowed
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "mysql-operator.fullname" . }}
  labels:
    app: {{ template "mysql-operator.name" . }}
    chart: {{ template "mysql-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mysql-operator.fullname" . }}
subjects:
  - name: {{ template "mysql-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end -}}
