apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: mysqlclusters.mysql.presslabs.org
spec:
  group: mysql.presslabs.org
  names:
    kind: MysqlCluster
    plural: mysqlclusters
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.readyNodes
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            backupSchedule:
              type: string
            backupScheduleJobsHistoryLimit:
              format: int64
              type: integer
            backupSecretName:
              type: string
            backupURL:
              type: string
            backupUri:
              type: string
            image:
              type: string
            initBucketSecretName:
              type: string
            initBucketURI:
              type: string
            maxSlaveLatency:
              format: int64
              type: integer
            minAvailable:
              type: string
            mysqlConf:
              type: object
            mysqlVersion:
              type: string
            podSpec:
              properties:
                affinity:
                  type: object
                annotations:
                  type: object
                imagePullPolicy:
                  type: string
                imagePullSecrets:
                  items:
                    type: object
                  type: array
                labels:
                  type: object
                nodeSelector:
                  type: object
                resources:
                  type: object
              type: object
            queryLimits:
              properties:
                ignoreCommands:
                  items:
                    type: string
                  type: array
                ignoreDb:
                  items:
                    type: string
                  type: array
                ignoreUser:
                  items:
                    type: string
                  type: array
                kill:
                  type: string
                killMode:
                  type: string
                maxIdleTime:
                  format: int64
                  type: integer
                maxQueryTime:
                  format: int64
                  type: integer
              required:
              - maxQueryTime
              type: object
            readOnly:
              type: boolean
            replicas:
              format: int32
              type: integer
            secretName:
              maxLength: 63
              minLength: 1
              type: string
            volumeSpec:
              properties:
                accessModes:
                  items:
                    type: string
                  type: array
                resources:
                  type: object
                selector:
                  type: object
                storageClassName:
                  type: string
                volumeMode:
                  type: string
                volumeName:
                  type: string
              type: object
          required:
          - secretName
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                - lastTransitionTime
                - reason
                - message
                type: object
              type: array
            nodes:
              items:
                properties:
                  conditions:
                    items:
                      properties:
                        lastTransitionTime:
                          format: date-time
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      - status
                      - lastTransitionTime
                      type: object
                    type: array
                  name:
                    type: string
                required:
                - name
                type: object
              type: array
            readyNodes:
              format: int64
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
