apiVersion: v1
description: A Helm chart for mysql operator
name: mysql-operator
keywords:
  - mysql
  - percona
  - orchestrator
  - presslabs
version: 0.1.10
home: https://github.com/presslabs/mysql-operator
sources:
  - https://github.com/presslabs/mysql-operator.git
appVersion: 0.1.10
